### ISSUE TITLE
Setting RUSTFMT in .cargo/config.toml

### ISSUE THREAD

**Issue by aDogCalledSpot** [schvv31n/yew-fmt#4]
Sorry that this issue doesn't directly relate to the code here but yew-fmt is working well for me and I would like to have `cargo fmt` default to using it in my Yew projects so collaborators have it working out of the box.

I tried the following:

```toml
# .cargo/config.toml

[env]
RUSTFMT = "yew-fmt"
```

But this doesn't appear to be working. The usual `RUSTFMT=yew-fmt cargo fmt` works fine.

Do you have any experience with this and maybe know what's happening?

**Comment by aDogCalledSpot** [comment]
Opened an issue in rustfmt as I believe this is probably a bug on their end: https://github.com/rust-lang/rustfmt/issues/5988

Will keep this open for other people interested. Close it if you like.

**Comment by schvv31n** [comment]
That's not a bug, but rather a documented nuance of how Cargo handles values passed to `[env]`, an example config in the docs shows the following:
```toml
[env]
# Set ENV_VAR_NAME=value for any process run by Cargo
ENV_VAR_NAME = "value"
```
It only passes those values through, but doesn't take them into account itself, so `cargo fmt` doesn't see that `RUSTFMT`, but `rustfmt` itself does, even though it doesn't handle it
